apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-demo
  namespace: platform-demo
  labels:
    app: platform-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: platform-demo
  template:
    metadata:
      labels:
        app: platform-demo
    spec:
      containers:
        - name: platform-demo
          image: hashicorp/http-echo:1.0
          args:
            - "-text=Platform Engineering Project 24"
            - "-listen=:5678"
          ports:
            - name: http
              containerPort: 5678
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
