apiVersion: v1
kind: Service
metadata:
  name: platform-demo
  namespace: platform-demo
spec:
  selector:
    app: platform-demo
  ports:
    - name: http
      port: 80
      targetPort: 5678
  type: ClusterIP
