apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 2

  selector:
    matchLabels:
      app: gitops-demo

  template:
    metadata:
      labels:
        app: gitops-demo

    spec:
      containers:
      - name: app
        image: 862087104485.dkr.ecr.us-east-1.amazonaws.com/wandy-docker-app:latest

        ports:
        - containerPort: 3000
