name: Deploy PROD

on:
  workflow_dispatch:

jobs:
  terraform-prod:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::862087104485:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: environments/prod
        run: terraform init

      - name: Terraform Format Check
        working-directory: environments/prod
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: environments/prod
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/prod
        run: terraform plan

      - name: Terraform Apply
        working-directory: environments/prod
        run: terraform apply -auto-approve
