name: Build and Deploy to ECS

on:
  push:
    paths:
      - 'project-8-docker-app/**'
      - '.github/workflows/deploy-ecs.yml'
  workflow_dispatch:

jobs:
  deploy-ecs:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: "862087104485"
      ECR_REPOSITORY: wandy-docker-app
      ECS_CLUSTER: wandy-ecs-cluster2
      ECS_SERVICE: wandy-docker-task-service
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::862087104485:role/github-actions-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG ./project-8-docker-app

      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Debug ECS values
        run: |
          echo "Cluster: $ECS_CLUSTER"
          echo "Service: $ECS_SERVICE"
          echo "Region: $AWS_REGION"
          aws ecs list-services --cluster $ECS_CLUSTER --region $AWS_REGION

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --desired-count 1 \
            --force-new-deployment \
            --region $AWS_REGION
